/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package motowarehouse.forms;

import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.util.Calendar;
import javax.swing.JOptionPane;
import motwarehouse.utils.CreditoModel;
import motwarehouse.utils.HandleStringsUtils;

/**
 *
 * @author Luis E. Vásquez
 */
public class FrmCredito extends javax.swing.JFrame {

    /**
     * Creates new form FrmCredito
     */
    public FrmCredito() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appLogo.png")));

        txtPrima.setText("0");
        txtInteres.setText("74");
    }
    
    private CreditoModel creditoData;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrima = new javax.swing.JFormattedTextField();
        lblPrecio1 = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblInteres = new javax.swing.JLabel();
        jsPlazos = new javax.swing.JSpinner();
        lblPrecio3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFechaFina = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        lblFechaCOmpra = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblMensaje = new javax.swing.JLabel();
        txtInteres = new javax.swing.JFormattedTextField();
        lblPorcentaje = new javax.swing.JLabel();
        lblPlazonFinImprimir = new javax.swing.JLabel();
        txtPrima1 = new javax.swing.JFormattedTextField();
        lblCouta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        txtPrima.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#######################"))));

        lblPrecio1.setText("Prima $:");

        lblHeader.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblHeader.setText("DATOS PARA CREDITO");

        lblInteres.setText("Interes:");

        jsPlazos.setModel(new javax.swing.SpinnerNumberModel(12, 12, 48, 1));
        jsPlazos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsPlazosStateChanged(evt);
            }
        });
        jsPlazos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jsPlazosPropertyChange(evt);
            }
        });

        lblPrecio3.setText("Plazos:");

        jLabel1.setText("Meses");

        lblFechaFina.setText("Plazo fin:");

        btnGuardar.setBackground(new java.awt.Color(204, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Cargar registro");
        btnGuardar.setMaximumSize(new java.awt.Dimension(4178, 4112));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblFechaCOmpra.setText("Fecha de compra:");

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        lblMensaje.setText("* Si no se ha cancelado la prima dejar el valor 0");

        txtInteres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#######################"))));
        txtInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInteresActionPerformed(evt);
            }
        });

        lblPorcentaje.setText("%");

        lblPlazonFinImprimir.setText(" - fecha -");

        txtPrima1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#######################"))));

        lblCouta.setText("Couta $:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblFechaCOmpra)
                                            .addComponent(lblPrecio1))
                                        .addComponent(lblCouta, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblPrecio3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFechaFina, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMensaje)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jsPlazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1))
                                            .addComponent(lblPlazonFinImprimir)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(txtPrima1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lblInteres)
                                .addGap(24, 24, 24)
                                .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPorcentaje))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaCOmpra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio1)
                    .addComponent(txtPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrima1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCouta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentaje)
                    .addComponent(lblInteres))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsPlazos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblPrecio3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlazonFinImprimir)
                    .addComponent(lblFechaFina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (formIsComplete()) {

            Calendar c = jDateChooser1.getCalendar();
            int meses = (int) jsPlazos.getValue();

            Double prima = Double.parseDouble(txtPrima.getText());
            Double couta = Double.parseDouble(txtPrima1.getText());
            Double interes = Double.parseDouble(txtInteres.getText());
            Integer plazos = (Integer) jsPlazos.getValue();

            // Cargamos el objeto con los datos
            creditoData = new CreditoModel(c, null, prima, couta, interes, plazos);

            c.add(Calendar.MONTH, meses);
            creditoData.setFechaPlazoFin(c);
            dispose();
            this.setVisible(false);
        }
        
        /*JOptionPane.showMessageDialog(null, "value " + HandleStringsUtils.converNumbersToLetter(txtPoliza.getText()),
                    "Advertencia", TrayIcon.MessageType.WARNING.ordinal());*/
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        Calendar c = jDateChooser1.getCalendar();

        if (jsPlazos.getValue() != null && c != null) {
            int meses = (int) jsPlazos.getValue();
            c.add(Calendar.MONTH, meses);

            lblPlazonFinImprimir.setText(HandleStringsUtils.formatearCalendar(c));
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jsPlazosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jsPlazosPropertyChange
        Calendar c = jDateChooser1.getCalendar();

        if (jsPlazos.getValue() != null && c != null) {
            int meses = (int) jsPlazos.getValue();
            c.add(Calendar.MONTH, meses);

            lblPlazonFinImprimir.setText(HandleStringsUtils.formatearCalendar(c));
        }
    }//GEN-LAST:event_jsPlazosPropertyChange

    private void jsPlazosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsPlazosStateChanged
        Calendar c = jDateChooser1.getCalendar();

        if (jsPlazos.getValue() != null && c != null) {
            int meses = (int) jsPlazos.getValue();
            c.add(Calendar.MONTH, meses);

            lblPlazonFinImprimir.setText(HandleStringsUtils.formatearCalendar(c));
        }
    }//GEN-LAST:event_jsPlazosStateChanged

    private void txtInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInteresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInteresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCredito().setVisible(true);
            }
        });
    }
    
    public boolean formIsComplete() {
        
        boolean val = true;
    
     if (jDateChooser1.getCalendar() == null) {

            JOptionPane.showMessageDialog(null, "Registre una fecha de compra",
                    "Advertencia", TrayIcon.MessageType.WARNING.ordinal());
            val = false;
        }
             
        if(val && txtPrima.getText().trim() == "") {
            JOptionPane.showMessageDialog(null, "Registre la prima",
                    "Advertencia", TrayIcon.MessageType.WARNING.ordinal());
            val = false;
        }
        
        if(val && txtPrima1.getText().trim() == "") {
            JOptionPane.showMessageDialog(null, "Registre la couta",
                    "Advertencia", TrayIcon.MessageType.WARNING.ordinal());
            val = false;
        }
        
        if(val && txtInteres.getText().trim() == "") {
            JOptionPane.showMessageDialog(null, "Registre el interes",
                    "Advertencia", TrayIcon.MessageType.WARNING.ordinal());
            val = false;
        }
    
        return val;
    }
    
    public CreditoModel getData() {
        return creditoData;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jsPlazos;
    private javax.swing.JLabel lblCouta;
    private javax.swing.JLabel lblFechaCOmpra;
    private javax.swing.JLabel lblFechaFina;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInteres;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblPlazonFinImprimir;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JFormattedTextField txtInteres;
    private javax.swing.JFormattedTextField txtPrima;
    private javax.swing.JFormattedTextField txtPrima1;
    // End of variables declaration//GEN-END:variables
}
